device: cuda
guidance_scale: 7.5
image_path: input_dir/summer-41.jpg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: null
output_path: output_dir/summer-41
pnp_attn_t: 0.3
pnp_f_t: 0.5
prompt: Mountains rise surrounded by trees clouds float above at winter
sd_version: '2.1'
seed: 1
