device: cuda
guidance_scale: 7.5
image_path: input_dir/autumn-36.jpg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: null
output_path: output_dir/autumn-36
pnp_attn_t: 0.3
pnp_f_t: 0.5
prompt: Field lies under sky with clouds at winter
sd_version: '2.1'
seed: 1
