device: cuda
guidance_scale: 7.5
image_path: input_dir/spring-33.jpg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: null
output_path: output_dir/spring-33
pnp_attn_t: 0.3
pnp_f_t: 0.5
prompt: Grass covered hills stand under sky with clouds two trees on hilltop at winter
sd_version: '2.1'
seed: 1
