device: cuda
guidance_scale: 7.5
image_path: input_dir/summer-34.jpg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: null
output_path: output_dir/summer-34
pnp_attn_t: 0.3
pnp_f_t: 0.5
prompt: Path winds through grass trees stand by ocean clouds cover sky at winter
sd_version: '2.1'
seed: 1
