device: cuda
guidance_scale: 7.5
image_path: input_dir/autumn-37.jpg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: null
output_path: output_dir/autumn-37
pnp_attn_t: 0.3
pnp_f_t: 0.5
prompt: Trees line path covered in leaves fog fills air at winter
sd_version: '2.1'
seed: 1
