device: cuda
guidance_scale: 7.5
image_path: input_dir/autumn-43.jpg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: null
output_path: output_dir/autumn-43
pnp_attn_t: 0.3
pnp_f_t: 0.5
prompt: People walk on hill surrounded by trees and houses in distance at winter
sd_version: '2.1'
seed: 1
