device: cuda
guidance_scale: 7.5
image_path: input_dir/summer-40.jpg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: null
output_path: output_dir/summer-40
pnp_attn_t: 0.3
pnp_f_t: 0.5
prompt: Clouds hover over field trees stand behind at winter
sd_version: '2.1'
seed: 1
